// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sgl.Infrastructure.Persistence;

#nullable disable

namespace Sgl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SglDbContext))]
    [Migration("20260927194859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Sgl.Domain.Carpeta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CiudadanoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaCitacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaSubida")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdoneidadMoral")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("Estado");

                    b.HasIndex("Sede");

                    b.ToTable("Carpetas", (string)null);
                });

            modelBuilder.Entity("Sgl.Domain.Ciudadano", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreBusqueda")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreBusqueda");

                    b.ToTable("Ciudadanos", (string)null);
                });

            modelBuilder.Entity("Sgl.Domain.HistorialCambio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anterior")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarpetaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nuevo")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaId");

                    b.ToTable("HistorialCambios", (string)null);
                });

            modelBuilder.Entity("Sgl.Domain.Carpeta", b =>
                {
                    b.HasOne("Sgl.Domain.Ciudadano", "Ciudadano")
                        .WithMany()
                        .HasForeignKey("CiudadanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudadano");
                });

            modelBuilder.Entity("Sgl.Domain.Ciudadano", b =>
                {
                    b.OwnsOne("Sgl.Domain.Rut", "Rut", b1 =>
                        {
                            b1.Property<Guid>("CiudadanoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("TEXT")
                                .HasColumnName("Rut");

                            b1.HasKey("CiudadanoId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Ciudadanos");

                            b1.WithOwner()
                                .HasForeignKey("CiudadanoId");
                        });

                    b.Navigation("Rut")
                        .IsRequired();
                });

            modelBuilder.Entity("Sgl.Domain.HistorialCambio", b =>
                {
                    b.HasOne("Sgl.Domain.Carpeta", null)
                        .WithMany("Historial")
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgl.Domain.Carpeta", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
